### ISSUE TITLE
Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by futureltj** [zhangshuiyong/nodequant#1]
运行时遇到问题：
module.js:602
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: %1 is not a valid Win32 application.
\\?\C:\my\nodequant\nodequant\model\client\CTP\NodeQuant.node
    at Object.Module._extensions..node (module.js:602:18)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by zhangshuiyong** [comment]
请到官网下载32位的v6.xx版本node.js 
https://nodejs.org/dist/v6.11.2/node-v6.11.2-x86.msi

**Comment by zhangshuiyong** [comment]
@futureltj 最新代码已经是1.1.0版本。支持32位和64位的Node.js v6了
