### ISSUE TITLE
NodeQuant.node源码有吗？

### ISSUE THREAD

**Issue by langhuihui** [zhangshuiyong/nodequant#3]
node 8下面加载NodeQuant.node失败了，不知道是不是nodejs版本问题
```
> NodeQuant@1.6.0 start E:\nodequant\nodequant
> node ./bin/www

CtpClient Node Addon Path:./CTP/win32/x64/NodeQuant.node
module.js:653
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified procedure could not be found.
\\?\E:\nodequant\nodequant\model\client\CTP\win32\x64\NodeQuant.node
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\nodequant\nodequant\model\client\CTPClient.js:10:10)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

**Comment by zhangshuiyong** [comment]
@langhuihui 请看教程和支持版本。nodequant现在只支持node v6.x。node8还不是lts版本，下个月才是，下个月才更新支持

**Comment by langhuihui** [comment]
NodeQuant.node的源码能提供吗？这样我可以自己编译

**Comment by QuantBull** [comment]
开放NodeQuant.node的源码很有必要，之所以选择开源就是不想受制于人，特别是金融交易框架，作者若希望更多人接受NodeQuant最好能开放源码，然后做好基于NodeQuant.node之上的组件方便用户开发策略。就像vnpy一样，先教用户如何编译出vnpy所依赖的交易所提供的基于python语言的交易接口。

**Comment by zhangshuiyong** [comment]
底层的ctp不可扩展非nodequant关注重点，希望用户多关注金融策略的开发和node.js层面的扩展和系统的稳定性

**Comment by jandykwan** [comment]
底层交易就是平台使用者最担心的。 会不会有后门，会不会本的扫描....
我们使用开源系统大多出发点就是一切在自己控制下，要不用个金字塔，做个开拓者就可以了，成本一点也不大，折腾其它平台，学习成本、开发成本都是很大的。
